{
 "title": "IIS_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "prediction_histogram_bucket",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "prediction_histogram_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prediction_request_latency_seconds_count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(prediction_request_latency_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "model_data_shift and model_accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_data_shift", "legendFormat": "__auto" },
    { "expr": "model_accuracy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "prediction_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}